#!/bin/bash
# WF 2020-04-29
pip=pip3
if [ "$USER" = "travis" ]
then
  pip=pip
fi
sudo -H $pip install -r requirements.txt
if [ ! -d schema ]
then
  git clone --single-branch --branch Conference_ID https://gitlab.com/crossref/schema
else
  cd schema
  git pull
fi
